version: '3.7'

services:
  psql:
    container_name: alcompare_psql
    image: postgres:16.2-alpine
    env_file: .env
    ports:
      - 5432:5432/tcp
    volumes:
      - alcompare_data:/var/lib/postgresql/data

volumes:
  alcompare_data:
